### PR TITLE
V2

### PR DESCRIPTION
**Pull request by p-j**
- **BREAKING**: Change the regex and logic to match phone numbers to prevent leakage
- Add a regex to disambiguate dates from phone numbers
- add `process` to `CensorifyIt`'s prototype to get the processed output directly
- **BREAKING**: modify how replacementText is used (repeat for single character vs as-is for multi char pattern)
- **BREAKING**: accept an array of exceptions that can be either RegExp or functions
- add tests

### CODE REVIEW

**Comment by p-j** [comment]
Next step:
- add ci with github action
- add coverage with codecov

**Comment by p-j** [comment]
> Looks really good ! I'd probably just add in the tests for security the both exceptions that we want to passe every time `eatwith.com` and `eat.lc`, so we know they won't get censored.

That's a test to be added on our implementation side (API)
This library is generic and doesn't care about our domain data.

**Comment by p-j** [comment]
> Look also good to me maybe you can just add a test with a text including numbers, in the previous version of the lib we had an issue with it -> for example "Dinner for 12 guests"

https://github.com/vizeat/censorify-it/pull/2/files#diff-2382a7144b80bd7c6cfe69ed37c02f0cR19-R83

Am I missing something here?

**Comment by bsenechal** [comment]
Sorry my comment wasn't really explicit. All your test have the numbers at the end. Maybe you should at least add one with "[text][number][text]"

**Comment by p-j** [comment]
@bsenechal can you tell me what makes you think the match could leak to the next word?

**Comment by bsenechal** [comment]
image
@p-j  ☝️

**Comment by p-j** [comment]
@bsenechal I should likely not have removed the .trim() call in the application of the repeat pattern
but still, this is not the same issue as the one you pointed out above.
The case you mention, the regex was matching text and not only numbers, the new phone regex cannot do that hence it is more safe to use and will not leak the same way. On top of that it ends the match by a word boundary (`\b`) meaning that after the first character that `\w` would match it will stop there unless the previous pattern would allow it.
This is why the pattern can match an ending white space because phone numbers can contain some, but it will never match the text after that.

**Pull request merged**
